version: '3.6'
services:
  maxdb:
    image: oracle/database:18.4.0-xe
    hostname: "${ENV_MAXDB_SERVICE_HOST}"
    shm_size: 1G
    environment:
      - "ORACLE_PWD=${ENV_DB_MAXIMO_PASSWORD}"
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - "ORACLE_CHARACTERSET=AL32UTF8"
    networks:
      - backend
    ports:
      - "${ENV_ORACLE_DB_PORT}:${ENV_ORACLE_DB_PORT}"
      - 5500:5500
      - 8080:8080
    volumes:
      - type: bind 
        source: ./oracle
        target: /opt/oracle/scripts/setup 

  maximo:
    image: "${ENV_NAMESPACE}/maximo:${ENV_MAXIMO_VER}"
    environment:
      - DB_VENDOR=Oracle
      - "MXINTADM_PASSWORD=${ENV_MXINTADM_PASSWORD}"
      - "MAXADMIN_PASSWORD=${ENV_MAXADMIN_PASSWORD}"
      - "MAXREG_PASSWORD=${ENV_MAXREG_PASSWORD}"
      - "MAXDB=${ENV_ORACLE_DB_INSTANCE}"
      - "DB_TABLE_SPACE=MAXDATA"
      - "DB_TEMP_SPACE=MAXTEMP"
      - "DB_INDEX_SPACE=MAXDATA"
      - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
      - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - UPDATE_APPS_ON_REBOOT=yes
      - KEEP_RUNNING=yes
      - "BASE_LANG=${ENV_BASE_LANG}"
      - "ADD_LANGS=${ENV_ADD_LANGS}"
      - "ADMIN_EMAIL_ADDRESS=${ENV_ADMIN_EMAIL_ADDRESS}"
      - "SMTP_SERVER_HOST_NAME=${ENV_SMTP_SERVER_HOST_NAME}"
      - "SKIN=${ENV_SKIN}"
      - "ENABLE_DEMO_DATA=${ENV_ENABLE_DEMO_DATA}"
    depends_on:
      - maxdb
    networks:
      - backend
    volumes:
      - maximo:/maximo

  maximo-ui:
    image: "${ENV_NAMESPACE}/maximo-ui:${ENV_MAXIMO_VER}"
    environment:
      - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
      - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
      - GEN_MAXIMO_PROPERTIES=no
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
      - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
      - LICENSE=accept
      - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
      - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
      - WLP_LOGGING_CONSOLE_LOGLEVEL=info
      - MXE_CRONTASK_DONOTRUN=ALL
    ports:
      - "9080:9080"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=maximo-docker-liberty_frontend"
      - "traefik.http.routers.maximo-ui.entrypoints=web"
      - "traefik.http.services.maximo-ui.loadbalancer.server.port=9080"
      - "traefik.http.routers.maximo-ui.rule=PathPrefix(`/maximo`) || PathPrefix(`/maximo-x`)"
    depends_on:
      - maxdb
      - jmsserver
    networks:
      frontend:
        aliases:
          - maximo-ui
      backend:
    volumes:
      - maximo:/maximo

  maximo-cron:
    image: "${ENV_NAMESPACE}/maximo-cron:${ENV_MAXIMO_VER}"
    environment:
      - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
      - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - GEN_MAXIMO_PROPERTIES=no
      - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
      - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
      - LICENSE=accept
      - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
      - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
    depends_on:
      - maxdb
      - jmsserver
    networks:
      frontend:
      backend:
    volumes:
      - maximo:/maximo

  # maximo-api:
  #   image: "${ENV_NAMESPACE}/maximo-api:${ENV_MAXIMO_VER}"
  #   environment:
  #     - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=no
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #     - MXE_CRONTASK_DONOTRUN=ALL
  #   ports:
  #     - "9081:9081"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=maximo-docker-liberty_frontend"
  #     - "traefik.http.routers.maximo-api.entrypoints=web"
  #     - "traefik.http.services.maximo-api.loadbalancer.server.port=9081"
  #     - "traefik.http.routers.maximo-api.rule=PathPrefix(`/maximoapi`)"
  #   depends_on:
  #     - maxdb
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-api
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  # maximo-report:
  #   image: "${ENV_NAMESPACE}/maximo-report:${ENV_MAXIMO_VER}"
  #   environment:
  #     - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=no
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #     - MXE_CRONTASK_DONOTRUN=ALL
  #   ports:
  #     - "9082:9081"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=maximo-docker-liberty_frontend"
  #     - "traefik.http.routers.maximo-report.entrypoints=web"
  #     - "traefik.http.services.maximo-report.loadbalancer.server.port=9082"
  #     - "traefik.http.routers.maximo-report.rule=PathPrefix(`/maximoreport`)"
  #   depends_on:
  #     - maxdb
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-report
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  # maximo-mea:
  #   image: "${ENV_NAMESPACE}/maximo-mea:${ENV_MAXIMO_VER}"
  #   environment:
  #     - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=no
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #     - MXE_CRONTASK_DONOTRUN=ALL
  #   ports:
  #     - "9084:9084"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=maximo-docker-liberty_frontend"
  #     - "traefik.http.routers.maximo-mea.entrypoints=web"
  #     - "traefik.http.services.maximo-mea.loadbalancer.server.port=9084"
  #     - "traefik.http.routers.maximo-mea.rule=PathPrefix(`/meaweb`)"
  #   depends_on:
  #     - maxdb
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #        - maximo-mea
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  # maximo-mea:
  #   image: "${ENV_NAMESPACE}/maximo-mea:${ENV_MAXIMO_VER}"
  #   environment:
  #     - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=no
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #     - MXE_CRONTASK_DONOTRUN=ALL
  #   ports:
  #     - "9084:9084"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=maximo-docker-liberty_frontend"
  #     - "traefik.http.routers.maximo-mea.entrypoints=web"
  #     - "traefik.http.services.maximo-mea.loadbalancer.server.port=9084"
  #     - "traefik.http.routers.maximo-mea.rule=PathPrefix(`/meaweb`)"
  #   depends_on:
  #     - maxdb
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #        - maximo-mea
  #     backend:
  #   volumes:
  #     - maximo:/maximo
  
  # maximo-jmsconsumer:
  #   image: "${ENV_NAMESPACE}/maximo-jmsconsumer:${ENV_MAXIMO_VER}"
  #   environment:
  #     - "MAXDB_SERVICE_PORT=${ENV_ORACLE_DB_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=no
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #     - MXE_CRONTASK_DONOTRUN=ALL
  #   ports:
  #     - "9083:9083"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=maximo-docker-liberty_frontend"
  #     - "traefik.http.routers.maximo-jmsconsumer.entrypoints=web"
  #     - "traefik.http.services.maximo-jmsconsumer.loadbalancer.server.port=9083"
  #     - "traefik.http.routers.maximo-jmsconsumer.rule=PathPrefix(`/maximojmsconsumer`)"
  #   depends_on:
  #     - maxdb
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-jmsconsumer
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  jmsserver:
    image: "${ENV_NAMESPACE}/jmsserver:20.0.0.3-kernel-java8-ibmjava"
    environment:
      - LICENSE=accept
      - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
      - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
      - "MAXIMO_JMS_SERVICE_SSL_PORT=${ENV_MAXIMO_JMS_SERVICE_SSL_PORT}"
    hostname: "${ENV_MAXIMO_JMS_SERVICE_HOST}"
    ports:
      - "${ENV_MAXIMO_JMS_SERVICE_PORT}:${ENV_MAXIMO_JMS_SERVICE_PORT}"
      - "${ENV_MAXIMO_JMS_SERVICE_SSL_PORT}:${ENV_MAXIMO_JMS_SERVICE_SSL_PORT}"
    networks:
      - frontend

  # frontend-proxy:
  #   image: "${ENV_NAMESPACE}/frontend-proxy:1.8"
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - maximo-ui
  #   networks:
  #     - frontend

  frontend-proxy:
    image: traefik:v2.2 # The official v2 Traefik docker image
    ports:
      - "80:80"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - frontend

networks:
  frontend:
  backend:
volumes:
  maxdb76:
  # Shared directory for liberty deployment files
  maximo:
